spring:
    datasource:
        url: jdbc:mysql://169.59.211.57:3306/pms
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect